using com.kizwiz.sipnsign.Models;

public class SignRepository
{
    public List<SignModel> GetSigns()
    {
        return new List<SignModel>
        {
            new SignModel { VideoPath = "actor.mp4", Choices = new List<string> { "Actor", "Performer", "Singer", "Dancer" }, CorrectAnswer = "Actor" },
            new SignModel { VideoPath = "again.mp4", Choices = new List<string> { "Once", "Again", "Repeat", "Return" }, CorrectAnswer = "Again" },
            new SignModel { VideoPath = "age.mp4", Choices = new List<string> { "Young", "Old", "Age", "Time" }, CorrectAnswer = "Age" },
            new SignModel { VideoPath = "angel.mp4", Choices = new List<string> { "Devil", "Angel", "Spirit", "Saint" }, CorrectAnswer = "Angel" },
            new SignModel { VideoPath = "answer.mp4", Choices = new List<string> { "Answer", "Question", "Reply", "Ask" }, CorrectAnswer = "Answer" },
            new SignModel { VideoPath = "argue.mp4", Choices = new List<string> { "Fight", "Argue", "Discuss", "Debate" }, CorrectAnswer = "Argue" },
            new SignModel { VideoPath = "autumn.mp4", Choices = new List<string> { "Winter", "Autumn", "Summer", "Spring" }, CorrectAnswer = "Autumn" },
            new SignModel { VideoPath = "bedroom.mp4", Choices = new List<string> { "Kitchen", "Bedroom", "Bathroom", "Living Room" }, CorrectAnswer = "Bedroom" },
            new SignModel { VideoPath = "beer.mp4", Choices = new List<string> { "Wine", "Beer", "Juice", "Water" }, CorrectAnswer = "Beer" },
            new SignModel { VideoPath = "birthday.mp4", Choices = new List<string> { "Anniversary", "Birthday", "Celebration", "Party" }, CorrectAnswer = "Birthday" },
            new SignModel { VideoPath = "breakfast.mp4", Choices = new List<string> { "Lunch", "Dinner", "Breakfast", "Snack" }, CorrectAnswer = "Breakfast" },
            new SignModel { VideoPath = "bus.mp4", Choices = new List<string> { "Bus", "Train", "Car", "Taxi" }, CorrectAnswer = "Bus" },
            new SignModel { VideoPath = "car.mp4", Choices = new List<string> { "Bicycle", "Car", "Motorcycle", "Bus" }, CorrectAnswer = "Car" },
            new SignModel { VideoPath = "chicken.mp4", Choices = new List<string> { "Chicken", "Fish", "Pork", "Beef" }, CorrectAnswer = "Chicken" },
            new SignModel { VideoPath = "dance.mp4", Choices = new List<string> { "Jump", "Dance", "Move", "Run" }, CorrectAnswer = "Dance" },
            new SignModel { VideoPath = "dolphin.mp4", Choices = new List<string> { "Whale", "Dolphin", "Shark", "Fish" }, CorrectAnswer = "Dolphin" },
            new SignModel { VideoPath = "dog.mp4", Choices = new List<string> { "Dog", "Cat", "Animal", "Bird" }, CorrectAnswer = "Dog" },
            new SignModel { VideoPath = "donkey.mp4", Choices = new List<string> { "Donkey", "Horse", "Zebra", "Mule" }, CorrectAnswer = "Donkey" },
            new SignModel { VideoPath = "forget.mp4", Choices = new List<string> { "Remember", "Forget", "Recall", "Learn" }, CorrectAnswer = "Forget" },
            new SignModel { VideoPath = "help.mp4", Choices = new List<string> { "Assist", "Help", "Support", "Aid" }, CorrectAnswer = "Help" },
            new SignModel { VideoPath = "read.mp4", Choices = new List<string> { "Write", "Read", "Speak", "Listen" }, CorrectAnswer = "Read" },
            new SignModel { VideoPath = "sun.mp4", Choices = new List<string> { "Sun", "Moon", "Star", "Cloud" }, CorrectAnswer = "Sun" },

            // New Entries
            new SignModel { VideoPath = "bicycle.mp4", Choices = new List<string> { "Car", "Bus", "Motorcycle", "Bicycle" }, CorrectAnswer = "Bicycle" },
            new SignModel { VideoPath = "brother.mp4", Choices = new List<string> { "Father", "Brother", "Friend", "Sister" }, CorrectAnswer = "Brother" },
            new SignModel { VideoPath = "chess.mp4", Choices = new List<string> { "Checkers", "Cards", "Dominoes", "Chess" }, CorrectAnswer = "Chess" },
            new SignModel { VideoPath = "child.mp4", Choices = new List<string> { "Teenager", "Baby", "Child", "Adult" }, CorrectAnswer = "Child" },
            new SignModel { VideoPath = "confused.mp4", Choices = new List<string> { "Sad", "Happy", "Angry", "Confused" }, CorrectAnswer = "Confused" },
            new SignModel { VideoPath = "dinner.mp4", Choices = new List<string> { "Dinner", "Lunch", "Snack", "Breakfast" }, CorrectAnswer = "Dinner" },
            new SignModel { VideoPath = "elephant.mp4", Choices = new List<string> { "Rhino", "Hippo", "Giraffe", "Elephant" }, CorrectAnswer = "Elephant" },
            new SignModel { VideoPath = "emergency.mp4", Choices = new List<string> { "Danger", "Accident", "Help", "Emergency" }, CorrectAnswer = "Emergency" },
            new SignModel { VideoPath = "England.mp4", Choices = new List<string> { "Ireland", "Wales", "England", "Scotland" }, CorrectAnswer = "England" },
            new SignModel { VideoPath = "evil.mp4", Choices = new List<string> { "Good", "Kind", "Bad", "Evil" }, CorrectAnswer = "Evil" },
            new SignModel { VideoPath = "fake.mp4", Choices = new List<string> { "True", "Fake", "Lie", "Real" }, CorrectAnswer = "Fake" },
            new SignModel { VideoPath = "family.mp4", Choices = new List<string> { "Group", "Neighbors", "Family", "Friends" }, CorrectAnswer = "Family" },
            new SignModel { VideoPath = "favourite2.mp4", Choices = new List<string> { "Hobby", "Favourite", "Choice", "Fever" }, CorrectAnswer = "Favourite" },
            new SignModel { VideoPath = "film.mp4", Choices = new List<string> { "Show", "Video", "Film", "Movie" }, CorrectAnswer = "Film" },
            new SignModel { VideoPath = "fire.mp4", Choices = new List<string> { "Flame", "Fire", "Smoke", "Heat" }, CorrectAnswer = "Fire" },
            new SignModel { VideoPath = "flower.mp4", Choices = new List<string> { "Tree", "Flower", "Leaf", "Bush" }, CorrectAnswer = "Flower" },
            new SignModel { VideoPath = "football2.mp4", Choices = new List<string> { "Rugby", "Volleyball", "Football", "Cricket" }, CorrectAnswer = "Football" },
            new SignModel { VideoPath = "fork.mp4", Choices = new List<string> { "Plate", "Spoon", "Fork", "Knife" }, CorrectAnswer = "Fork" },
            new SignModel { VideoPath = "giraffe.mp4", Choices = new List<string> { "Camel", "Zebra", "Elephant", "Giraffe" }, CorrectAnswer = "Giraffe" },
            new SignModel { VideoPath = "guitar.mp4", Choices = new List<string> { "Piano", "Drums", "Violin", "Guitar" }, CorrectAnswer = "Guitar" },
            new SignModel { VideoPath = "Halloween.mp4", Choices = new List<string> { "Christmas", "Thanksgiving", "Halloween", "Easter" }, CorrectAnswer = "Halloween" },
            new SignModel { VideoPath = "heart.mp4", Choices = new List<string> { "Brain", "Lung", "Heart", "Liver" }, CorrectAnswer = "Heart" },
            new SignModel { VideoPath = "horrible.mp4", Choices = new List<string> { "Great", "Terrible", "Bad", "Horrible" }, CorrectAnswer = "Horrible" },
            new SignModel { VideoPath = "hot.mp4", Choices = new List<string> { "Cool", "Cold", "Warm", "Hot" }, CorrectAnswer = "Hot" },
            new SignModel { VideoPath = "interview.mp4", Choices = new List<string> { "Test", "Exam", "Interview", "Meeting" }, CorrectAnswer = "Interview" },
            new SignModel { VideoPath = "jail.mp4", Choices = new List<string> { "Court", "Prison", "Cell", "Jail" }, CorrectAnswer = "Jail" },
            new SignModel { VideoPath = "kitchen.mp4", Choices = new List<string> { "Bedroom", "Living Room", "Kitchen", "Bathroom" }, CorrectAnswer = "Kitchen" },
            new SignModel { VideoPath = "knife.mp4", Choices = new List<string> { "Spoon", "Knife", "Blade", "Fork" }, CorrectAnswer = "Knife" },
            new SignModel { VideoPath = "know.mp4", Choices = new List<string> { "Know", "Understand", "Remember", "Forget" }, CorrectAnswer = "Know" },
            new SignModel { VideoPath = "learn.mp4", Choices = new List<string> { "Learn", "Teach", "Study", "Understand" }, CorrectAnswer = "Learn" },
            new SignModel { VideoPath = "Lion.mp4", Choices = new List<string> { "Tiger", "Leopard", "Lion", "Cheetah" }, CorrectAnswer = "Lion" },
            new SignModel { VideoPath = "lose.mp4", Choices = new List<string> { "Win", "Lose", "Fail", "Miss" }, CorrectAnswer = "Lose" },
            new SignModel { VideoPath = "lost.mp4", Choices = new List<string> { "Lost", "Found", "Confused", "Gone" }, CorrectAnswer = "Lost" },
            new SignModel { VideoPath = "love.mp4", Choices = new List<string> { "Love", "Hate", "Like", "Adore" }, CorrectAnswer = "Love" },
            new SignModel { VideoPath = "lunch.mp4", Choices = new List<string> { "Lunch", "Dinner", "Breakfast", "Brunch" }, CorrectAnswer = "Lunch" },
            new SignModel { VideoPath = "middle.mp4", Choices = new List<string> { "Middle", "Centre", "Side", "Edge" }, CorrectAnswer = "Middle" },
            new SignModel { VideoPath = "miserable.mp4", Choices = new List<string> { "Unhappy", "Miserable", "Sad", "Upset" }, CorrectAnswer = "Miserable" },
            new SignModel { VideoPath = "money.mp4", Choices = new List<string> { "Coins", "Money", "Cash", "Wealth" }, CorrectAnswer = "Money" },
            new SignModel { VideoPath = "monkey.mp4", Choices = new List<string> { "Monkey", "Gorilla", "Chimp", "Baboon" }, CorrectAnswer = "Monkey" },
            new SignModel { VideoPath = "music.mp4", Choices = new List<string> { "Beat", "Sound", "Dance", "Music" }, CorrectAnswer = "Music" },
            new SignModel { VideoPath = "name.mp4", Choices = new List<string> { "Title", "Word", "Name", "Call" }, CorrectAnswer = "Name" },
            new SignModel { VideoPath = "nothing.mp4", Choices = new List<string> { "Nothing", "Anything", "Everything", "Something" }, CorrectAnswer = "Nothing" },
            new SignModel { VideoPath = "parents.mp4", Choices = new List<string> { "Relatives", "Siblings", "Family", "Parents" }, CorrectAnswer = "Parents" },
            new SignModel { VideoPath = "penguin.mp4", Choices = new List<string> { "Seal", "Bird", "Penguin", "Duck" }, CorrectAnswer = "Penguin" },
            new SignModel { VideoPath = "phone.mp4", Choices = new List<string> { "Talk", "Ring", "Call", "Phone" }, CorrectAnswer = "Phone" },
            new SignModel { VideoPath = "pig.mp4", Choices = new List<string> { "Boar", "Sheep", "Cow", "Pig" }, CorrectAnswer = "Pig" },
            new SignModel { VideoPath = "pigeon.mp4", Choices = new List<string> { "Bird", "Crow", "Dove", "Pigeon" }, CorrectAnswer = "Pigeon" },
            new SignModel { VideoPath = "police.mp4", Choices = new List<string> { "Guard", "Officer", "Law", "Police" }, CorrectAnswer = "Police" },
            new SignModel { VideoPath = "poor.mp4", Choices = new List<string> { "Broke", "Wealthy", "Poor", "Rich" }, CorrectAnswer = "Poor" },
            new SignModel { VideoPath = "posh.mp4", Choices = new List<string> { "Fancy", "Elegant", "Posh", "Simple" }, CorrectAnswer = "Posh" },
            new SignModel { VideoPath = "question.mp4", Choices = new List<string> { "Ask", "Answer", "Reply", "Question" }, CorrectAnswer = "Question" },
            new SignModel { VideoPath = "rabbit.mp4", Choices = new List<string> { "Hare", "Squirrel", "Deer", "Rabbit" }, CorrectAnswer = "Rabbit" },
            new SignModel { VideoPath = "radio.mp4", Choices = new List<string> { "Talk", "Music", "Radio", "News" }, CorrectAnswer = "Radio" },
            new SignModel { VideoPath = "rugby.mp4", Choices = new List<string> { "Hockey", "Football", "Rugby", "Cricket" }, CorrectAnswer = "Rugby" },
            new SignModel { VideoPath = "Scotland.mp4", Choices = new List<string> { "Wales", "England", "Ireland", "Scotland" }, CorrectAnswer = "Scotland" },
            new SignModel { VideoPath = "sea.mp4", Choices = new List<string> { "River", "Lake", "Ocean", "Sea" }, CorrectAnswer = "Sea" },
            new SignModel { VideoPath = "sex.mp4", Choices = new List<string> { "Relationship", "Love", "Sex", "Gender" }, CorrectAnswer = "Sex" },
            new SignModel { VideoPath = "shower.mp4", Choices = new List<string> { "Rain", "Wash", "Bath", "Shower" }, CorrectAnswer = "Shower" },
            new SignModel { VideoPath = "silence.mp4", Choices = new List<string> { "Mute", "Peace", "Quiet", "Silence" }, CorrectAnswer = "Silence" },
            new SignModel { VideoPath = "sister.mp4", Choices = new List<string> { "Cousin", "Brother", "Sibling", "Sister" }, CorrectAnswer = "Sister" },
            new SignModel { VideoPath = "sleep.mp4", Choices = new List<string> { "Nap", "Rest", "Dream", "Sleep" }, CorrectAnswer = "Sleep" },
            new SignModel { VideoPath = "smile.mp4", Choices = new List<string> { "Grin", "Smile", "Laugh", "Happy" }, CorrectAnswer = "Smile" },
            new SignModel { VideoPath = "spring.mp4", Choices = new List<string> { "Winter", "Spring", "Autumn", "Summer" }, CorrectAnswer = "Spring" },
            new SignModel { VideoPath = "stone.mp4", Choices = new List<string> { "Rock", "Pebble", "Stone", "Boulder" }, CorrectAnswer = "Stone" },
            new SignModel { VideoPath = "summer.mp4", Choices = new List<string> { "Autumn", "Summer", "Winter", "Spring" }, CorrectAnswer = "Summer" },
            new SignModel { VideoPath = "tease.mp4", Choices = new List<string> { "Tease", "Mock", "Laugh", "Play" }, CorrectAnswer = "Tease" },
            new SignModel { VideoPath = "tiger.mp4", Choices = new List<string> { "Cheetah", "Leopard", "Lion", "Tiger" }, CorrectAnswer = "Tiger" },
            new SignModel { VideoPath = "trust.mp4", Choices = new List<string> { "Faith", "Trust", "Believe", "Loyalty" }, CorrectAnswer = "Trust" },
            new SignModel { VideoPath = "ugly.mp4", Choices = new List<string> { "Pretty", "Unattractive", "Beautiful", "Ugly" }, CorrectAnswer = "Ugly" },
            new SignModel { VideoPath = "university.mp4", Choices = new List<string> { "University", "School", "College", "Academy" }, CorrectAnswer = "University" },
            new SignModel { VideoPath = "vodka.mp4", Choices = new List<string> { "Vodka", "Whiskey", "Rum", "Tequila" }, CorrectAnswer = "Vodka" },
            new SignModel { VideoPath = "Wales.mp4", Choices = new List<string> { "Wales", "Scotland", "Ireland", "England" }, CorrectAnswer = "Wales" },
            new SignModel { VideoPath = "walk.mp4", Choices = new List<string> { "Walk", "Run", "Stroll", "March" }, CorrectAnswer = "Walk" },
            new SignModel { VideoPath = "want.mp4", Choices = new List<string> { "Want", "Need", "Desire", "Wish" }, CorrectAnswer = "Want" },
            new SignModel { VideoPath = "weather.mp4", Choices = new List<string> { "Weather", "Climate", "Rain", "Temperature" }, CorrectAnswer = "Weather" },
            new SignModel { VideoPath = "wedding.mp4", Choices = new List<string> { "Wedding", "Marriage", "Ceremony", "Engagement" }, CorrectAnswer = "Wedding" },
            new SignModel { VideoPath = "Weird.mp4", Choices = new List<string> { "Weird", "Strange", "Odd", "Unusual" }, CorrectAnswer = "Weird" },
            new SignModel { VideoPath = "when.mp4", Choices = new List<string> { "When", "Where", "Why", "What" }, CorrectAnswer = "When" },
            new SignModel { VideoPath = "where.mp4", Choices = new List<string> { "Where", "When", "Why", "What" }, CorrectAnswer = "Where" },
            new SignModel { VideoPath = "why.mp4", Choices = new List<string> { "Why", "What", "How", "When" }, CorrectAnswer = "Why" },
            new SignModel { VideoPath = "win.mp4", Choices = new List<string> { "Win", "Lose", "Score", "Victory" }, CorrectAnswer = "Win" },
            new SignModel { VideoPath = "winter.mp4", Choices = new List<string> { "Winter", "Summer", "Spring", "Autumn" }, CorrectAnswer = "Winter" },
            new SignModel { VideoPath = "work.mp4", Choices = new List<string> { "Work", "Job", "Task", "Duty" }, CorrectAnswer = "Work" },
        };
    }
}
